### ISSUE TITLE
Doesn't find any beacons anymore(v0.3)

### ISSUE THREAD

**Issue by Sennevds** [turbo-lab/android-beacon-mqtt#32]
After updating to version 0.3 from the play store it doesn't find my esp32 and RPI beacons anymore.
Tried to remove and reinstall but same thing. No logging is shown on the mainscreen and I only can set the location permission to: 'Allow only while using the app' instead of 'Allways'

Edit:
App also crashes when trying to manually add a beacon

**Comment by turbulator** [comment]
Sorry about that. I'll fix as soon as possible.

**Comment by turbulator** [comment]
Fixed in 0.3 build 20

**Comment by Sennevds** [comment]
The latest version fixes the problem with location permission but still doesn't find beacons and crashes when I try to manually add one

**Comment by Sennevds** [comment]
I've let it crash a few times so I could send a crash report(I tried to get a logcat with adb but my usb-c port isn't working good) Hopefully you get the report and get some extra information

**Comment by turbulator** [comment]
I've already got it.

**Comment by turbulator** [comment]
Fixed in 0.3 build 21. Could you confirm?

**Comment by Sennevds** [comment]
Fixed!

**Comment by turbulator** [comment]
Great!
